plantuml.jar:
	wget -O plantuml.jar http://sourceforge.net/projects/plantuml/files/plantuml.jar/download

clariahservice.png: clariahservice.uml plantuml.jar
	java -jar plantuml.jar clariahservice.uml
